import{i as a,S as f}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();function d(s){const r="https://pixabay.com/api/",t=s.trim().split(",").join("+"),n=new URLSearchParams({key:"42920910-4418ce5fcb505a601cb14954f",q:[t],image_type:"photo",orientation:"horizontal",safesearch:!0});u();const e=`${r}?${n}`;return fetch(e).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}function h(s){if(s.length===0)a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const r=s.map(t=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${t.largeImageURL}">
            <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
            </ul>
            </li>`).join("");m.insertAdjacentHTML("beforeend",r),y.refresh()}}const c=document.querySelector(".search-form"),m=document.querySelector(".gallery"),y=new f(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".loader");l.style.display="none";const u=()=>{l.style.display="flex"},p=()=>{l.style.display="none"};c.addEventListener("submit",g);function g(s){s.preventDefault(),m.innerHTML="";const r=c.elements.search.value.trim();r!==""?(u(),d(r).then(t=>{h(t.hits),p(),c.reset()}).catch(t=>{console.error(t),p(),a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})})):a.error({message:"Please complete the field!",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
