import{i as a,S as u}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();function d(s){const r=s.trim().split(",").join("+"),e=new URLSearchParams({key:"42920910-4418ce5fcb505a601cb14954f",q:[r],image_type:"photo",orientation:"horizontal",safesearch:!0});return f(),fetch(`https://pixabay.com/api/?${e}`).then(n=>{if(!n.ok)throw new Error(n.status);return n.json()})}function h(s){if(s.length===0)a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const r=s.map(e=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${e.largeImageURL}">
            <img class="photo" src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${e.likes}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${e.views}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${e.comments}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${e.downloads}</p></li>
            </ul>
            </li>`).join("");m.insertAdjacentHTML("beforeend",r),y.refresh()}}const c=document.querySelector(".search-form"),m=document.querySelector(".gallery"),y=new u(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".loader");l.style.display="none";const f=()=>{l.style.display="flex"},p=()=>{l.style.display="none"};c.addEventListener("submit",g);function g(s){s.preventDefault(),m.innerHTML="";const r=c.elements.search.value.trim();r!==""?(f(),d(r).then(e=>{h(e.hits),p(),c.reset()}).catch(e=>{console.error(e),p(),a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})})):a.error({message:"Please complete the field!",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
