import{i,S as m}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();function p(){const r=f.value.trim().split(",").join("+"),s=new URLSearchParams({key:"42920910-4418ce5fcb505a601cb14954f",q:[r],image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${s}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function u(r){if(r.length===0)i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const s=r.map(e=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${e.largeImageURL}">
            <img class="photo" src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${e.likes}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${e.views}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${e.comments}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${e.downloads}</p></li>
            </ul>
            </li>`).join("");l.insertAdjacentHTML("beforeend",s),h.refresh()}}const a=document.querySelector(".search-form"),f=a.elements.search,l=document.querySelector(".gallery"),h=new m(".gallery a",{captionsData:"alt",captionDelay:250});a.addEventListener("submit",d);function d(r){r.preventDefault(),l.innerHTML="",r.target.elements.search.value.trim()!==""?(window.onload=()=>{p().then(e=>{u(e.hits)}).catch(e=>{console.log(e),i.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})})},window.onload(),a.reset()):i.error({message:"Please complete the field!",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
